tabela: iris.csv
modelos:
  - "nome_modelo": modelo_lm
    "y": Sepal.Length
    "x": [Sepal.Width, Petal.Length]
    "tipo": linear
  - "nome_modelo": modelo_np
    "y": Sepal.Length
    "x": [Sepal.Width]
    "tipo": np
    "metodo_np":
  - "nome_modelo": modelo_lasso
    "y": Sepal.Length
    "x": [Sepal.Width, Petal.Length]
    "tipo": lasso
     



