tabela: iris.csv
modelos:
  - "nome_modelo": modelo1
    "y": Sepal.Length
    "x": [Sepal.Width, Petal.Length]
    "tipo": linear
  - "nome_modelo": modelo2
    "y": Sepal.Length
    "x": [Sepal.Width, Petal.Length]
    "tipo": linear
    "metodo_np":
  - "nome_modelo": modelo3
    "y": Sepal.Length
    "x": [Sepal.Width, Petal.Length]
    "tipo": linear
     



